### ISSUE TITLE
Investigate possibility for CI/CD pipeline for SMAD Terraform scripts

### ISSUE THREAD

**Issue by hjhsalo** [smaddis/smad-deploy-azure#13]
We should investigate a bit could we benefit from a CI/CD pipeline which automatically updates SMAD cloud stuff.

Examples of such pipeline using Github Actions, Azure DevOps and good old Travis-CI below:
https://medium.com/swlh/lets-do-devops-github-actions-terraform-aws-77ef6078e4f2
https://medium.com/faun/lets-do-devops-build-an-azure-devops-terraform-pipeline-part-1-2-9ab301f3923c
https://medium.com/swlh/intro-to-travisci-with-terraform-80e65cf975fe

**Comment by msrn** [comment]
More info for consideration:

https://learn.hashicorp.com/tutorials/terraform/github-actions
https://www.blendmastersoftware.com/blog/deploying-to-azure-using-terraform-and-github-actions
